In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv("/content/Churn_Modelling.csv")

In [ ]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [ ]:
#one hot encoding on gender and geography since it is a string

In [ ]:
df=pd.get_dummies(df,columns=["Geography","Gender"],drop_first=True,dtype=int)

In [ ]:
df=df.drop(["Surname"],axis=1)

In [ ]:
df.head()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,1,15634602,619,42,2,0.00,1,1,1,101348.88,1,0,0,0
1,2,15647311,608,41,1,83807.86,1,0,1,112542.58,0,0,1,0
2,3,15619304,502,42,8,159660.80,3,1,0,113931.57,1,0,0,0
3,4,15701354,699,39,1,0.00,2,0,0,93826.63,0,0,0,0
4,5,15737888,850,43,2,125510.82,1,1,1,79084.10,0,0,1,0

In [ ]:
#scaling

In [ ]:
x=df.drop(["Exited"],axis=1)
y=df["Exited"]

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [ ]:
x=sc.fit_transform(x)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
x_train = np.delete(x_train, [0, 1], axis=1)
x_test = np.delete(x_test, [0, 1], axis=1)

In [ ]:
x_train

array([[ 0.17042381, -0.4693113 , -0.00442596, ..., -0.57873591,
         1.74273971, -1.09598752],
       [-2.31280236,  0.29351742, -1.38753759, ...,  1.72790383,
        -0.57380915,  0.91241915],
       [-1.19535058, -0.94607926, -1.04175968, ..., -0.57873591,
        -0.57380915, -1.09598752],
       ...,
       [ 0.90504489, -0.37395771, -0.00442596, ..., -0.57873591,
        -0.57380915,  0.91241915],
       [-0.62627792, -0.08789694,  1.37868567, ..., -0.57873591,
         1.74273971, -1.09598752],
       [-0.28483432,  0.86563897, -1.38753759, ...,  1.72790383,
        -0.57380915, -1.09598752]])

In [ ]:
x_train.shape

(8000, 11)

MLP

In [ ]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
model=Sequential()

In [ ]:
model.add(Dense(3,activation="sigmoid",input_dim=11))
model.add(Dense(1,activation="sigmoid"))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 3)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 40 (160.00 B)

 Trainable params: 40 (160.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(optimizer="Adam",loss="binary_crossentropy")

In [ ]:
model.fit(x_train,y_train,epochs=20)

Epoch 1/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.7919
Epoch 2/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.5965
Epoch 3/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.5087
Epoch 4/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4712
Epoch 5/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4541
Epoch 6/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4452
Epoch 7/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4397
Epoch 8/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4360
Epoch 9/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4332
Epoch 10/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4310
Epoch 11/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.4293
Epoch 12/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4280
Epoch 13/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4268
Epoch 14/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4255
Epoch 15/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4242
Epoch 16/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4229
Epoch 17/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4214
Epoch 18/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4198
Epoch 19/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4182
Epoch 20/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4165

In [ ]:
 model.get_weights()

[array([[ 0.12854692, -0.17355965,  0.08056586],
        [-0.6646963 ,  2.3231666 ,  2.056035  ],
        [ 0.03384525, -0.25795138, -0.11875099],
        [ 0.20021904,  0.4439514 ,  0.36715472],
        [ 0.9829518 ,  0.33064538,  0.34727615],
        [-0.12356149, -0.14154755, -0.2340207 ],
        [ 0.9487891 , -0.14662859, -0.35238442],
        [-0.19789182, -0.17610244, -0.17175165],
        [-0.7791008 ,  0.17778572,  0.45028526],
        [-0.0507627 ,  0.200881  , -0.07671661],
        [ 0.36122864, -0.33223978, -0.4784837 ]], dtype=float32),
 array([ 1.234981  , -0.47974765, -0.51379836], dtype=float32),
 array([[-2.0501592 ],
        [ 1.0138392 ],
        [ 0.81889814]], dtype=float32),
 array([-0.8800088], dtype=float32)]

In [ ]:
model.layers[0].get_weights()

[array([[ 0.12854692, -0.17355965,  0.08056586],
        [-0.6646963 ,  2.3231666 ,  2.056035  ],
        [ 0.03384525, -0.25795138, -0.11875099],
        [ 0.20021904,  0.4439514 ,  0.36715472],
        [ 0.9829518 ,  0.33064538,  0.34727615],
        [-0.12356149, -0.14154755, -0.2340207 ],
        [ 0.9487891 , -0.14662859, -0.35238442],
        [-0.19789182, -0.17610244, -0.17175165],
        [-0.7791008 ,  0.17778572,  0.45028526],
        [-0.0507627 ,  0.200881  , -0.07671661],
        [ 0.36122864, -0.33223978, -0.4784837 ]], dtype=float32),
 array([ 1.234981  , -0.47974765, -0.51379836], dtype=float32)]

In [ ]:
print(f"The model has {len(model.layers)} layers.")

The model has 2 layers.

In [ ]:
y_log=model.predict(x_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [ ]:
y_log

array([[0.22664107],
       [0.38139924],
       [0.16701205],
       ...,
       [0.13098128],
       [0.12016387],
       [0.23932813]], dtype=float32)

In [ ]:
y_pred=np.where(y_log>0.5,1,0)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.826